services:
  actsm:
    image: ${IMAGE:-actsm-a1}
    build:
      context: .
      platforms:
        - ${PLATFORM:-linux/amd64}
    volumes:
      - .:/code
    ports:
      - "8888:8888"
      - "8000:8000"
    command: >-
      bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"
    stdin_open: true
    tty: true
